environment: production
environmentCode:
name: bng-api-prototype
namespace: bng-api
workstream: bng-api
image: bng-api-prototype

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: bng-api-prototype-config-map

containerSecret:
  name: bng-api-prototype-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3000

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5
