services:
  bng-api-prototype:
    build:
      context: .
      target: production
    image: bng-api-prototype
    container_name: bng-api-prototype
    environment:
      APPINSIGHTS_CLOUDROLE: bng-api-prototype-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
